/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// OrderReshopRepriceMedia media type (default view)
type OrderReshopRepriceMedia struct {

	Benefits *Benefit `json:"benefits,omitempty"`

	// A hash of surcharges indexed by the credit card type.
	CardSurcharges interface{} `json:"cardSurcharges,omitempty"`

	Disclosures []Disclosure `json:"disclosures,omitempty"`

	// Flight Segment information. Including departure, arrival and airline information.
	Flights []Flight `json:"flights,omitempty"`

	// The ID for this offer
	OfferID string `json:"offerID,omitempty"`

	// The code of the provider that is really offering the flight
	Owner string `json:"owner,omitempty"`

	Price *Price `json:"price,omitempty"`

	// List of services that indicate for which segment the ancillaries must be re-booked
	SeatsToRebook []AncillariesToRebook `json:"seatsToRebook,omitempty"`

	// List of services that indicate for which segment the ancillaries must be re-booked
	ServicesToRebook []AncillariesToRebook `json:"servicesToRebook,omitempty"`

	Warnings []OrderLog `json:"warnings,omitempty"`
}
