/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ItineraryRs struct {

	// Created at unix time
	CreatedAt int64 `json:"createdAt,omitempty"`

	// route details
	Flights []ItineraryFlight `json:"flights,omitempty"`

	// Max number of stops
	MaxNumberOfStops int64 `json:"maxNumberOfStops,omitempty"`

	// Offer type
	OfferType string `json:"offerType,omitempty"`

	// possible fare options for itinerary
	Options []ItineraryOption `json:"options,omitempty"`

	// 2-letter code of provider
	Owner string `json:"owner,omitempty"`

	// Payment time limit, after this time created order will become expired
	PaymentTimeLimit string `json:"paymentTimeLimit,omitempty"`
}
