/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// OfferPriceMedia media type (default view)
type OfferPriceMedia struct {

	AgencyData *AgencyData `json:"agencyData,omitempty"`

	AllowedPaymentMethods *AllowedPaymentMethods `json:"allowedPaymentMethods,omitempty"`

	AllowedRequests *OfferPriceAllowedRequests `json:"allowedRequests,omitempty"`

	Benefits *Benefit `json:"benefits,omitempty"`

	// A hash of surcharges indexed by the credit card type.
	CardSurcharges interface{} `json:"cardSurcharges,omitempty"`

	// Unix time of created datetime
	CreatedAt int64 `json:"createdAt,omitempty"`

	Disclosures []Disclosure `json:"disclosures,omitempty"`

	Discounts *DiscountPreferences `json:"discounts,omitempty"`

	// A Bundle of fields which are not mandatory for all airlines, in that way, the API will check the airline config and return them.
	ExtraInfoMandatory []string `json:"extraInfoMandatory,omitempty"`

	// Flight Segment information. Including departure, arrival and airline information.
	Flights []Flight `json:"flights,omitempty"`

	// Instant payment field indicates agency has auto-issuing with 'agencyCash' or 'agencyCard' enabled. If this field is presented, payment method will be automatically selected
	InstantPayment string `json:"instantPayment,omitempty"`

	// Offer expiration time
	OfferExpiration string `json:"offerExpiration,omitempty"`

	// The ID for this offer
	OfferID string `json:"offerID,omitempty"`

	// The code of the provider that is really offering the flight
	Owner string `json:"owner,omitempty"`

	// List of referenced travelers
	Passengers []Passenger `json:"passengers,omitempty"`

	// Payment time limit
	PaymentTimeLimit string `json:"paymentTimeLimit,omitempty"`

	Price *Price `json:"price,omitempty"`

	Remarks *OfferPriceRemarks `json:"remarks,omitempty"`

	// The ID of the response. Usually needed on the OrderCreate request (few providers don´t need it).
	ShoppingResponseID string `json:"shoppingResponseID,omitempty"`

	// List of ancillaries allowed on pre-booking stage
	SpecialServices []Ssr `json:"specialServices,omitempty"`

	Warnings []OrderLog `json:"warnings,omitempty"`
}
