/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ExitSeat struct {

	// If the exit is on the right or in the left of the plane
	Position string `json:"position,omitempty"`

	// The row where the exit in placed
	Row int64 `json:"row,omitempty"`

	// The resference to the segment 
	SegmentID string `json:"segmentID,omitempty"`
}
