/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OrderListCounters struct {

	Active int64 `json:"active,omitempty"`

	Approved int64 `json:"approved,omitempty"`

	Cancelled int64 `json:"cancelled,omitempty"`

	Disrupted int64 `json:"disrupted,omitempty"`

	Pending int64 `json:"pending,omitempty"`

	Refused int64 `json:"refused,omitempty"`

	Ticketed int64 `json:"ticketed,omitempty"`

	UnderApproval int64 `json:"underApproval,omitempty"`

	Unused int64 `json:"unused,omitempty"`

	Voided int64 `json:"voided,omitempty"`
}
