/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Travelers struct {

	// Number of adult passengers - older than 12 yo
	ADT float64 `json:"ADT"`

	// Number of children - older than 2 yo
	CHD float64 `json:"CHD,omitempty"`

	// Number of infants - younger than 2 yo
	INF float64 `json:"INF,omitempty"`

	// Number of young adults for Tour Operators - 12-16 yo
	V14 float64 `json:"V14,omitempty"`

	// Number of adult passengers for Tour Operators - older than 12 yo
	VFR float64 `json:"VFR,omitempty"`

	// Number of infants for Tour Operators - younger than 2 yo
	VNF float64 `json:"VNF,omitempty"`

	// Number of children for Tour Operators - older than 2 yo
	VNN float64 `json:"VNN,omitempty"`

	// Number of young adults - 12-16 yo
	YAD float64 `json:"YAD,omitempty"`
}
