/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// ItineraryRQ is an object for flight
type ItineraryRq struct {

	// Departure airport IATA 3-letter code
	Arrival string `json:"arrival"`

	// Departure/Arrival date in format YYYY-MM-DD.
	Date string `json:"date"`

	// Departure airport IATA 3-letter code
	Departure string `json:"departure"`

	// Flight numbers for itinerary
	FlightNumbers []string `json:"flightNumbers,omitempty"`
}
