/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"fmt"
	"net/http"
	"strings"

	"github.com/gorilla/mux"
)

type Route struct {
	Name        string
	Method      string
	Pattern     string
	HandlerFunc http.HandlerFunc
}

type Routes []Route

func NewRouter() *mux.Router {
	router := mux.NewRouter().StrictSlash(true)
	for _, route := range routes {
		var handler http.Handler
		handler = route.HandlerFunc
		handler = Logger(handler, route.Name)

		router.
			Methods(route.Method).
			Path(route.Pattern).
			Name(route.Name).
			Handler(handler)
	}

	return router
}

func Index(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello World!")
}

var routes = Routes{
	Route{
		"Index",
		"GET",
		"/v1.2/",
		Index,
	},

	Route{
		"AirDocIssuePost",
		strings.ToUpper("Post"),
		"/v1.2/AirDocIssue",
		AirDocIssuePost,
	},

	Route{
		"AirShoppingPost",
		strings.ToUpper("Post"),
		"/v1.2/AirShopping",
		AirShoppingPost,
	},

	Route{
		"OfferPricePost",
		strings.ToUpper("Post"),
		"/v1.2/OfferPrice",
		OfferPricePost,
	},

	Route{
		"OrderCancelPost",
		strings.ToUpper("Post"),
		"/v1.2/OrderCancel",
		OrderCancelPost,
	},

	Route{
		"OrderChangePost",
		strings.ToUpper("Post"),
		"/v1.2/OrderChange",
		OrderChangePost,
	},

	Route{
		"OrderCreatePost",
		strings.ToUpper("Post"),
		"/v1.2/OrderCreate",
		OrderCreatePost,
	},

	Route{
		"OrderReshopPost",
		strings.ToUpper("Post"),
		"/v1.2/OrderReshop",
		OrderReshopPost,
	},

	Route{
		"OrderReshopRefundPost",
		strings.ToUpper("Post"),
		"/v1.2/OrderReshopRefund",
		OrderReshopRefundPost,
	},

	Route{
		"OrderReshopRepricePost",
		strings.ToUpper("Post"),
		"/v1.2/OrderReshopReprice",
		OrderReshopRepricePost,
	},

	Route{
		"OrderRetrievePost",
		strings.ToUpper("Post"),
		"/v1.2/OrderRetrieve",
		OrderRetrievePost,
	},

	Route{
		"OrderUpdatePost",
		strings.ToUpper("Post"),
		"/v1.2/OrderUpdate",
		OrderUpdatePost,
	},

	Route{
		"SeatAvailabilityPost",
		strings.ToUpper("Post"),
		"/v1.2/SeatAvailability",
		SeatAvailabilityPost,
	},

	Route{
		"ServiceListPost",
		strings.ToUpper("Post"),
		"/v1.2/ServiceList",
		ServiceListPost,
	},

	Route{
		"ItinShoppingPost",
		strings.ToUpper("Post"),
		"/v1.2/ItinShopping",
		ItinShoppingPost,
	},

	Route{
		"OrderCommentsPost",
		strings.ToUpper("Post"),
		"/v1.2/OrderComments",
		OrderCommentsPost,
	},

	Route{
		"OrderFileGET",
		strings.ToUpper("Get"),
		"/v1.2/OrderFile",
		OrderFileGET,
	},

	Route{
		"OrderHistoryGET",
		strings.ToUpper("Get"),
		"/v1.2/OrderHistory",
		OrderHistoryGET,
	},

	Route{
		"OrderListGET",
		strings.ToUpper("Get"),
		"/v1.2/OrderList",
		OrderListGET,
	},

	Route{
		"OrderMetasPost",
		strings.ToUpper("Post"),
		"/v1.2/OrderMetas",
		OrderMetasPost,
	},

	Route{
		"OrderRemarksPost",
		strings.ToUpper("Post"),
		"/v1.2/OrderRemarks",
		OrderRemarksPost,
	},

	Route{
		"OrderReviewPost",
		strings.ToUpper("Post"),
		"/v1.2/OrderReview",
		OrderReviewPost,
	},

	Route{
		"ProviderListGET",
		strings.ToUpper("Get"),
		"/v1.2/ProviderList",
		ProviderListGET,
	},

	Route{
		"StatusGet",
		strings.ToUpper("Get"),
		"/v1.2/status",
		StatusGet,
	},
}
