// THIS FILE IS AUTO GENERATED BY GK-CLI DO NOT EDIT!!
package grpc

import (
	endpoint "carier/pkg/endpoint"
	pb "carier/pkg/grpc/pb"
	grpc "github.com/go-kit/kit/transport/grpc"
)

// NewGRPCServer makes a set of endpoints available as a gRPC AddServer
type grpcServer struct {
	createAirlineCompany grpc.Handler
	deleteAirlineCompany grpc.Handler
	getAirlineCompany    grpc.Handler
	listAirlineCompany   grpc.Handler
	pb.UnimplementedCarierServer
}

func NewGRPCServer(endpoints endpoint.Endpoints, options map[string][]grpc.ServerOption) pb.CarierServer {
	return &grpcServer{
		createAirlineCompany: makeCreateAirlineCompanyHandler(endpoints, options["CreateAirlineCompany"]),
		deleteAirlineCompany: makeDeleteAirlineCompanyHandler(endpoints, options["DeleteAirlineCompany"]),
		getAirlineCompany:    makeGetAirlineCompanyHandler(endpoints, options["GetAirlineCompany"]),
		listAirlineCompany:   makeListAirlineCompanyHandler(endpoints, options["ListAirlineCompany"]),
	}
}
