// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.1
// source: carier.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAirlineCompanyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company_ID  int64                  `protobuf:"varint,1,opt,name=company_ID,json=companyID,proto3" json:"company_ID,omitempty"`
	CompanyName string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	IataCode    string                 `protobuf:"bytes,3,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` //    string mainAirport = 4;
}

func (x *CreateAirlineCompanyRequest) Reset() {
	*x = CreateAirlineCompanyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAirlineCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirlineCompanyRequest) ProtoMessage() {}

func (x *CreateAirlineCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirlineCompanyRequest.ProtoReflect.Descriptor instead.
func (*CreateAirlineCompanyRequest) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAirlineCompanyRequest) GetCompany_ID() int64 {
	if x != nil {
		return x.Company_ID
	}
	return 0
}

func (x *CreateAirlineCompanyRequest) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *CreateAirlineCompanyRequest) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *CreateAirlineCompanyRequest) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type CreateAirlineCompanyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company_ID int64 `protobuf:"varint,1,opt,name=company_ID,json=companyID,proto3" json:"company_ID,omitempty"`
}

func (x *CreateAirlineCompanyReply) Reset() {
	*x = CreateAirlineCompanyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAirlineCompanyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAirlineCompanyReply) ProtoMessage() {}

func (x *CreateAirlineCompanyReply) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAirlineCompanyReply.ProtoReflect.Descriptor instead.
func (*CreateAirlineCompanyReply) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAirlineCompanyReply) GetCompany_ID() int64 {
	if x != nil {
		return x.Company_ID
	}
	return 0
}

type DeleteAirlineCompanyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company_ID int64 `protobuf:"varint,1,opt,name=company_ID,json=companyID,proto3" json:"company_ID,omitempty"`
}

func (x *DeleteAirlineCompanyRequest) Reset() {
	*x = DeleteAirlineCompanyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAirlineCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAirlineCompanyRequest) ProtoMessage() {}

func (x *DeleteAirlineCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAirlineCompanyRequest.ProtoReflect.Descriptor instead.
func (*DeleteAirlineCompanyRequest) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteAirlineCompanyRequest) GetCompany_ID() int64 {
	if x != nil {
		return x.Company_ID
	}
	return 0
}

type DeleteAirlineCompanyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company_ID int64 `protobuf:"varint,1,opt,name=company_ID,json=companyID,proto3" json:"company_ID,omitempty"`
}

func (x *DeleteAirlineCompanyReply) Reset() {
	*x = DeleteAirlineCompanyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAirlineCompanyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAirlineCompanyReply) ProtoMessage() {}

func (x *DeleteAirlineCompanyReply) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAirlineCompanyReply.ProtoReflect.Descriptor instead.
func (*DeleteAirlineCompanyReply) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteAirlineCompanyReply) GetCompany_ID() int64 {
	if x != nil {
		return x.Company_ID
	}
	return 0
}

type GetAirlineCompanyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company_ID int64 `protobuf:"varint,1,opt,name=company_ID,json=companyID,proto3" json:"company_ID,omitempty"`
}

func (x *GetAirlineCompanyRequest) Reset() {
	*x = GetAirlineCompanyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAirlineCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirlineCompanyRequest) ProtoMessage() {}

func (x *GetAirlineCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirlineCompanyRequest.ProtoReflect.Descriptor instead.
func (*GetAirlineCompanyRequest) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{4}
}

func (x *GetAirlineCompanyRequest) GetCompany_ID() int64 {
	if x != nil {
		return x.Company_ID
	}
	return 0
}

type GetAirlineCompanyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company_ID  int64                  `protobuf:"varint,1,opt,name=company_ID,json=companyID,proto3" json:"company_ID,omitempty"`
	CompanyName string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	IataCode    string                 `protobuf:"bytes,3,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` //    string mainAirport = 4;
}

func (x *GetAirlineCompanyReply) Reset() {
	*x = GetAirlineCompanyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAirlineCompanyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAirlineCompanyReply) ProtoMessage() {}

func (x *GetAirlineCompanyReply) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAirlineCompanyReply.ProtoReflect.Descriptor instead.
func (*GetAirlineCompanyReply) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{5}
}

func (x *GetAirlineCompanyReply) GetCompany_ID() int64 {
	if x != nil {
		return x.Company_ID
	}
	return 0
}

func (x *GetAirlineCompanyReply) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *GetAirlineCompanyReply) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *GetAirlineCompanyReply) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListAirlineCompanyRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListAirlineCompanyRequest) Reset() {
	*x = ListAirlineCompanyRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAirlineCompanyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAirlineCompanyRequest) ProtoMessage() {}

func (x *ListAirlineCompanyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAirlineCompanyRequest.ProtoReflect.Descriptor instead.
func (*ListAirlineCompanyRequest) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{6}
}

type ListAirlineCompanyReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AirlineOmpany []*AirlineCompanyPrams `protobuf:"bytes,1,rep,name=airline_ompany,json=airlineOmpany,proto3" json:"airline_ompany,omitempty"`
}

func (x *ListAirlineCompanyReply) Reset() {
	*x = ListAirlineCompanyReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAirlineCompanyReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAirlineCompanyReply) ProtoMessage() {}

func (x *ListAirlineCompanyReply) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAirlineCompanyReply.ProtoReflect.Descriptor instead.
func (*ListAirlineCompanyReply) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{7}
}

func (x *ListAirlineCompanyReply) GetAirlineOmpany() []*AirlineCompanyPrams {
	if x != nil {
		return x.AirlineOmpany
	}
	return nil
}

type AirlineCompanyPrams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Company_ID  int64                  `protobuf:"varint,1,opt,name=company_ID,json=companyID,proto3" json:"company_ID,omitempty"`
	CompanyName string                 `protobuf:"bytes,2,opt,name=company_name,json=companyName,proto3" json:"company_name,omitempty"`
	IataCode    string                 `protobuf:"bytes,3,opt,name=iata_code,json=iataCode,proto3" json:"iata_code,omitempty"`
	CreatedAt   *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"` //    string mainAirport = 4;
}

func (x *AirlineCompanyPrams) Reset() {
	*x = AirlineCompanyPrams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carier_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AirlineCompanyPrams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AirlineCompanyPrams) ProtoMessage() {}

func (x *AirlineCompanyPrams) ProtoReflect() protoreflect.Message {
	mi := &file_carier_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AirlineCompanyPrams.ProtoReflect.Descriptor instead.
func (*AirlineCompanyPrams) Descriptor() ([]byte, []int) {
	return file_carier_proto_rawDescGZIP(), []int{8}
}

func (x *AirlineCompanyPrams) GetCompany_ID() int64 {
	if x != nil {
		return x.Company_ID
	}
	return 0
}

func (x *AirlineCompanyPrams) GetCompanyName() string {
	if x != nil {
		return x.CompanyName
	}
	return ""
}

func (x *AirlineCompanyPrams) GetIataCode() string {
	if x != nil {
		return x.IataCode
	}
	return ""
}

func (x *AirlineCompanyPrams) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

var File_carier_proto protoreflect.FileDescriptor

var file_carier_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x63, 0x61, 0x72, 0x69, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02,
	0x70, 0x62, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0xb7, 0x01, 0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69,
	0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x44, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x61, 0x74, 0x61, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x3a, 0x0a,
	0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x22, 0x3c, 0x0a, 0x1b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x22, 0x3a, 0x0a, 0x19, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f,
	0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x49, 0x44, 0x22, 0x39, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x22, 0xb2,
	0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d,
	0x70, 0x61, 0x6e, 0x79, 0x5f, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x49, 0x44, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69,
	0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x69, 0x61, 0x74, 0x61, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67,
	0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x41, 0x74, 0x22, 0x1b, 0x0a, 0x19, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x69,
	0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x59, 0x0a, 0x17, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43,
	0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3e, 0x0a, 0x0e, 0x61,
	0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65,
	0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x72, 0x61, 0x6d, 0x73, 0x52, 0x0d, 0x61, 0x69,
	0x72, 0x6c, 0x69, 0x6e, 0x65, 0x4f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x22, 0xaf, 0x01, 0x0a, 0x13,
	0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x50, 0x72,
	0x61, 0x6d, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x49,
	0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x49, 0x44, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6d, 0x70, 0x61, 0x6e,
	0x79, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x61, 0x74, 0x61, 0x5f, 0x63, 0x6f,
	0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x61, 0x74, 0x61, 0x43, 0x6f,
	0x64, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61,
	0x6d, 0x70, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x32, 0xe1, 0x02,
	0x0a, 0x0e, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x12, 0x56, 0x0a, 0x14, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e,
	0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61,
	0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70,
	0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x56, 0x0a, 0x14, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79,
	0x12, 0x1f, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x69, 0x72, 0x6c,
	0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x69, 0x72,
	0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x4d, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x1c, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x69,
	0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x69, 0x72, 0x6c,
	0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12,
	0x50, 0x0a, 0x12, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f,
	0x6d, 0x70, 0x61, 0x6e, 0x79, 0x12, 0x1d, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41,
	0x69, 0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1b, 0x2e, 0x70, 0x62, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x69,
	0x72, 0x6c, 0x69, 0x6e, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x6e, 0x79, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x14, 0x5a, 0x12, 0x63, 0x61, 0x72, 0x69, 0x65, 0x72, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_carier_proto_rawDescOnce sync.Once
	file_carier_proto_rawDescData = file_carier_proto_rawDesc
)

func file_carier_proto_rawDescGZIP() []byte {
	file_carier_proto_rawDescOnce.Do(func() {
		file_carier_proto_rawDescData = protoimpl.X.CompressGZIP(file_carier_proto_rawDescData)
	})
	return file_carier_proto_rawDescData
}

var file_carier_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_carier_proto_goTypes = []interface{}{
	(*CreateAirlineCompanyRequest)(nil), // 0: pb.CreateAirlineCompanyRequest
	(*CreateAirlineCompanyReply)(nil),   // 1: pb.CreateAirlineCompanyReply
	(*DeleteAirlineCompanyRequest)(nil), // 2: pb.DeleteAirlineCompanyRequest
	(*DeleteAirlineCompanyReply)(nil),   // 3: pb.DeleteAirlineCompanyReply
	(*GetAirlineCompanyRequest)(nil),    // 4: pb.GetAirlineCompanyRequest
	(*GetAirlineCompanyReply)(nil),      // 5: pb.GetAirlineCompanyReply
	(*ListAirlineCompanyRequest)(nil),   // 6: pb.ListAirlineCompanyRequest
	(*ListAirlineCompanyReply)(nil),     // 7: pb.ListAirlineCompanyReply
	(*AirlineCompanyPrams)(nil),         // 8: pb.AirlineCompanyPrams
	(*timestamppb.Timestamp)(nil),       // 9: google.protobuf.Timestamp
}
var file_carier_proto_depIdxs = []int32{
	9, // 0: pb.CreateAirlineCompanyRequest.created_at:type_name -> google.protobuf.Timestamp
	9, // 1: pb.GetAirlineCompanyReply.created_at:type_name -> google.protobuf.Timestamp
	8, // 2: pb.ListAirlineCompanyReply.airline_ompany:type_name -> pb.AirlineCompanyPrams
	9, // 3: pb.AirlineCompanyPrams.created_at:type_name -> google.protobuf.Timestamp
	0, // 4: pb.AirlineCompany.CreateAirlineCompany:input_type -> pb.CreateAirlineCompanyRequest
	2, // 5: pb.AirlineCompany.DeleteAirlineCompany:input_type -> pb.DeleteAirlineCompanyRequest
	4, // 6: pb.AirlineCompany.GetAirlineCompany:input_type -> pb.GetAirlineCompanyRequest
	6, // 7: pb.AirlineCompany.ListAirlineCompany:input_type -> pb.ListAirlineCompanyRequest
	1, // 8: pb.AirlineCompany.CreateAirlineCompany:output_type -> pb.CreateAirlineCompanyReply
	3, // 9: pb.AirlineCompany.DeleteAirlineCompany:output_type -> pb.DeleteAirlineCompanyReply
	5, // 10: pb.AirlineCompany.GetAirlineCompany:output_type -> pb.GetAirlineCompanyReply
	7, // 11: pb.AirlineCompany.ListAirlineCompany:output_type -> pb.ListAirlineCompanyReply
	8, // [8:12] is the sub-list for method output_type
	4, // [4:8] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_carier_proto_init() }
func file_carier_proto_init() {
	if File_carier_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_carier_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAirlineCompanyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAirlineCompanyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAirlineCompanyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAirlineCompanyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAirlineCompanyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAirlineCompanyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAirlineCompanyRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAirlineCompanyReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carier_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AirlineCompanyPrams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_carier_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carier_proto_goTypes,
		DependencyIndexes: file_carier_proto_depIdxs,
		MessageInfos:      file_carier_proto_msgTypes,
	}.Build()
	File_carier_proto = out.File
	file_carier_proto_rawDesc = nil
	file_carier_proto_goTypes = nil
	file_carier_proto_depIdxs = nil
}
