// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// CarierClient is the client API for Carier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CarierClient interface {
	CreateAirlineCompany(ctx context.Context, in *CreateAirlineCompanyRequest, opts ...grpc.CallOption) (*CreateAirlineCompanyReply, error)
	DeleteAirlineCompany(ctx context.Context, in *DeleteAirlineCompanyRequest, opts ...grpc.CallOption) (*DeleteAirlineCompanyReply, error)
	GetAirlineCompany(ctx context.Context, in *GetAirlineCompanyRequest, opts ...grpc.CallOption) (*GetAirlineCompanyReply, error)
	ListAirlineCompany(ctx context.Context, in *ListAirlineCompanyRequest, opts ...grpc.CallOption) (*ListAirlineCompanyReply, error)
}

type carierClient struct {
	cc grpc.ClientConnInterface
}

func NewCarierClient(cc grpc.ClientConnInterface) CarierClient {
	return &carierClient{cc}
}

func (c *carierClient) CreateAirlineCompany(ctx context.Context, in *CreateAirlineCompanyRequest, opts ...grpc.CallOption) (*CreateAirlineCompanyReply, error) {
	out := new(CreateAirlineCompanyReply)
	err := c.cc.Invoke(ctx, "/pb.Carier/CreateAirlineCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carierClient) DeleteAirlineCompany(ctx context.Context, in *DeleteAirlineCompanyRequest, opts ...grpc.CallOption) (*DeleteAirlineCompanyReply, error) {
	out := new(DeleteAirlineCompanyReply)
	err := c.cc.Invoke(ctx, "/pb.Carier/DeleteAirlineCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carierClient) GetAirlineCompany(ctx context.Context, in *GetAirlineCompanyRequest, opts ...grpc.CallOption) (*GetAirlineCompanyReply, error) {
	out := new(GetAirlineCompanyReply)
	err := c.cc.Invoke(ctx, "/pb.Carier/GetAirlineCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *carierClient) ListAirlineCompany(ctx context.Context, in *ListAirlineCompanyRequest, opts ...grpc.CallOption) (*ListAirlineCompanyReply, error) {
	out := new(ListAirlineCompanyReply)
	err := c.cc.Invoke(ctx, "/pb.Carier/ListAirlineCompany", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarierServer is the server API for Carier service.
// All implementations must embed UnimplementedCarierServer
// for forward compatibility
type CarierServer interface {
	CreateAirlineCompany(context.Context, *CreateAirlineCompanyRequest) (*CreateAirlineCompanyReply, error)
	DeleteAirlineCompany(context.Context, *DeleteAirlineCompanyRequest) (*DeleteAirlineCompanyReply, error)
	GetAirlineCompany(context.Context, *GetAirlineCompanyRequest) (*GetAirlineCompanyReply, error)
	ListAirlineCompany(context.Context, *ListAirlineCompanyRequest) (*ListAirlineCompanyReply, error)
	mustEmbedUnimplementedCarierServer()
}

// UnimplementedCarierServer must be embedded to have forward compatible implementations.
type UnimplementedCarierServer struct {
}

func (UnimplementedCarierServer) CreateAirlineCompany(context.Context, *CreateAirlineCompanyRequest) (*CreateAirlineCompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAirlineCompany not implemented")
}
func (UnimplementedCarierServer) DeleteAirlineCompany(context.Context, *DeleteAirlineCompanyRequest) (*DeleteAirlineCompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAirlineCompany not implemented")
}
func (UnimplementedCarierServer) GetAirlineCompany(context.Context, *GetAirlineCompanyRequest) (*GetAirlineCompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAirlineCompany not implemented")
}
func (UnimplementedCarierServer) ListAirlineCompany(context.Context, *ListAirlineCompanyRequest) (*ListAirlineCompanyReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAirlineCompany not implemented")
}
func (UnimplementedCarierServer) mustEmbedUnimplementedCarierServer() {}

// UnsafeCarierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CarierServer will
// result in compilation errors.
type UnsafeCarierServer interface {
	mustEmbedUnimplementedCarierServer()
}

func RegisterCarierServer(s grpc.ServiceRegistrar, srv CarierServer) {
	s.RegisterService(&Carier_ServiceDesc, srv)
}

func _Carier_CreateAirlineCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAirlineCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarierServer).CreateAirlineCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Carier/CreateAirlineCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarierServer).CreateAirlineCompany(ctx, req.(*CreateAirlineCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carier_DeleteAirlineCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAirlineCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarierServer).DeleteAirlineCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Carier/DeleteAirlineCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarierServer).DeleteAirlineCompany(ctx, req.(*DeleteAirlineCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carier_GetAirlineCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAirlineCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarierServer).GetAirlineCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Carier/GetAirlineCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarierServer).GetAirlineCompany(ctx, req.(*GetAirlineCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Carier_ListAirlineCompany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAirlineCompanyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarierServer).ListAirlineCompany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pb.Carier/ListAirlineCompany",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarierServer).ListAirlineCompany(ctx, req.(*ListAirlineCompanyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Carier_ServiceDesc is the grpc.ServiceDesc for Carier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Carier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.Carier",
	HandlerType: (*CarierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAirlineCompany",
			Handler:    _Carier_CreateAirlineCompany_Handler,
		},
		{
			MethodName: "DeleteAirlineCompany",
			Handler:    _Carier_DeleteAirlineCompany_Handler,
		},
		{
			MethodName: "GetAirlineCompany",
			Handler:    _Carier_GetAirlineCompany_Handler,
		},
		{
			MethodName: "ListAirlineCompany",
			Handler:    _Carier_ListAirlineCompany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "carier/pkg/grpc/pb/carier.proto",
}
