/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// OrderReshopRefundMedia media type (default view)
type OrderReshopRefundMedia struct {
	// Flight Segment information. Including departure, arrival and airline information.
	Flights []Flight `json:"flights,omitempty"`
	OriginalOrder *Price `json:"originalOrder,omitempty"`
	Penalty *Price `json:"penalty,omitempty"`
	Refund *Price `json:"refund,omitempty"`
	// List of seats
	Seats []Seat `json:"seats,omitempty"`
	// List of services
	Services []Service `json:"services,omitempty"`
	// Tickets information
	Tickets []TicketInfo `json:"tickets,omitempty"`
	// Some airlines returns the voiding option in the OrderReshop Refund. In this way, this field indicates if the OrderCancel will be executed.
	VoidPermited bool `json:"voidPermited,omitempty"`
	Warnings []OrderLog `json:"warnings,omitempty"`
}
