/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Passenger struct {
	Data *PassengerData `json:"data,omitempty"`
	Document *Document `json:"document,omitempty"`
	// FareBasisCodes
	FareBasisCodes interface{} `json:"fareBasisCodes,omitempty"`
	Identity4Discount []Identity4Discount `json:"identity4Discount,omitempty"`
	// Infant reference (if any)
	InfantReference string `json:"infantReference,omitempty"`
	PassengerType string `json:"passengerType,omitempty"`
	Seats []Seat `json:"seats,omitempty"`
	Services []ServiceRequest `json:"services,omitempty"`
	SpecialServices []Ssr `json:"specialServices,omitempty"`
	// Traveler reference from ServiceList response
	TravelerReference string `json:"travelerReference"`
}
