/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PassengerData struct {
	Address *Address `json:"address,omitempty"`
	// Birthdate using format YYYY-MM-DD.
	Birthdate string `json:"birthdate,omitempty"`
	Email string `json:"email,omitempty"`
	FqtvInfo *FqtvInfo `json:"fqtvInfo,omitempty"`
	// Valid values: 
	Gender string `json:"gender,omitempty"`
	Name string `json:"name"`
	// Phone number
	Phone string `json:"phone,omitempty"`
	Surname string `json:"surname,omitempty"`
	// Valid Values: 
	Title string `json:"title,omitempty"`
}
