/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type OfferPricePayload struct {
	OfferID string `json:"offerID,omitempty"`
	OfferIDs []string `json:"offerIDs,omitempty"`
	// The offerID provided in OrderReshopReprice response on the rebooking process. Used on the rebooking flow and order has services or seats to get the final real price of the re-offer and the services/seats.
	ReshopOfferID string `json:"reshopOfferID,omitempty"`
	// List of service objects (used on the rebooking flow only with some airlines)
	Services []ServiceRequest `json:"services,omitempty"`
}
