/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// SeatAvailabilityMedia media type (default view)
type SeatAvailabilityMedia struct {
	Disclosures []Disclosure `json:"disclosures,omitempty"`
	// Exit rows position
	Exits []ExitSeat `json:"exits,omitempty"`
	// The owner of the segment flight that the SeatAvailability is requesting
	Owner string `json:"owner,omitempty"`
	// Info about seat display (rows and columns)
	SeatDisplay []SeatDisplay `json:"seatDisplay,omitempty"`
	// Info about seats location, description, characteristics, price...
	SeatList []Seat `json:"seatList,omitempty"`
	// Info about flight segments
	Segments []FlightSegment `json:"segments,omitempty"`
}
