/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type ItineraryFlightSegment struct {
	// Origin destination reference
	ODRef string `json:"ODRef,omitempty"`
	Detail *ItineraryFlightSegmentDetail `json:"detail,omitempty"`
	Equipment *Equipment `json:"equipment,omitempty"`
	// Flight number of airline
	FlightNumber string `json:"flightNumber,omitempty"`
	MarketingCarrier *MarketingCarrier `json:"marketingCarrier,omitempty"`
	OperatingCarrier *OperatingCarrier `json:"operatingCarrier,omitempty"`
	OriginDestination *OriginDestinationRsInner `json:"originDestination,omitempty"`
	// Segment ID
	SegmentID string `json:"segmentID,omitempty"`
}
