/*
 * AirGateway NDC JSON API
 *
 * This API allows shopping and booking with IATA's New Distribution Capabilities (NDC) standard. It provides aggregated shopping capabilities (AirShopping), detailed offer description (OfferPrice), flight seat selection (SeatAvailability) and booking flight reservations (OrderCreate). Some fields in our API (when noticed) use the PADIS Standard v16.1. Find more information <a href=http://www.iata.org/whatwedo/workgroups/Pages/padis.aspx>here</a>
 *
 * API version: 1.2
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type PriceDetailBreakdown struct {
	// The base price, without any taxes (300 or 300.32)
	Base float64 `json:"base,omitempty"`
	// The ID for each offer
	OfferItemID string `json:"offerItemID,omitempty"`
	// Passenger references
	PassengerRefs string `json:"passengerRefs,omitempty"`
	// The passenger type
	PassengerType string `json:"passengerType,omitempty"`
	// The total sum of all surcharges (6 or 6.05)
	Surcharge float64 `json:"surcharge,omitempty"`
	Tax *PriceDetailTax `json:"tax,omitempty"`
}
